name: Strapi

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: ./api

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    # - name: Copy uploads folder
    #   run: |
    #     cp -r public/uploads /home/ubuntu/adobefashion/
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: NODE_ENV=production NODE_OPTIONS=--max_old_space_size=8192 npm run build --if-present
    # - name: Copy back uploads folder
    #   run: |
    #     cp -a /home/ubuntu/adobefashion/uploads/. public/uploads/
    # - run: NODE_ENV=production /home/boris/.nvm/versions/node/v14.15.1/bin/pm2 restart strandbeestAPI
